
[phases.setup]
nixPkgs = ['bun']
aptPkgs = ['build-essential']

[phases.install]
cmds = ['bun install --ignore-scripts --frozen-lockfile']

[phases.build]
cmds = ['bun run build']  # Fixed: was 'build run build'

[start]
cmd = 'bun run build/index.js'



