"use client";

import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  type ReactNode,
} from "react";
import {
  Loader2,
  Plus,
  Trash2,
  AlertTriangle,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  Sparkles,
  Sun,
  Moon,
  CircleDot,
  Check,
  X,
  Lightbulb,
  ListChecks,
  Scale,
  MousePointerClick,
  Eraser,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetTitle,
} from "@/components/ui/sheet";
import { cn } from "@/lib/utils";
import { sanitizeTimetableUserMessage } from "@/lib/utils/timetable-user-messages";
import { tt } from "../utils/timetableTheme";
import type { Grade, Subject, Teacher } from "@/lib/types/timetable";
import type {
  TeacherLessonAllocation,
  TeacherWorkloadRules,
  TimetablePreflightResult,
  PreferredTimeOfDay,
} from "@/lib/types/timetable-allocation";
import { computeLocalPreflight } from "../utils/allocationPreflight";
import {
  resolveTenantGradeLevelIdForApi,
  resolveTenantStreamIdForApi,
  tenantStreamIdsForGrade,
} from "../utils/resolveGradeForSchoolConfig";
import {
  TimetableWeeklyLessonsPlanner,
  type TimetableWeeklyLessonsPlannerHandle,
} from "./TimetableWeeklyLessonsPlanner";
import { useToast } from "@/components/ui/use-toast";

interface TimetableAutoGenerateDrawerProps {
  open: boolean;
  onClose: () => void;
  /** Which step to land on when the drawer opens (0 = demand, 1 = rules, 2 = generate). */
  initialStep?: number;
  /** Shown in the header so the wizard stays tied to the grid, e.g. "Baby Class · A". */
  scopeLabel?: string;
  focusedGradeId?: string | null;
  onFocusedGradeChange?: (gradeId: string) => void;
  termId: string;
  teachers: Teacher[];
  subjects: Subject[];
  grades: Grade[];
  availableSlotsPerClass: number;
  schoolDays?: number;
  periodNumbers?: number[];
  allocations: TeacherLessonAllocation[];
  rules: TeacherWorkloadRules[];
  loading: boolean;
  onCreateAllocation: (input: {
    termId: string;
    teacherId: string;
    subjectId: string;
    gradeLevelId: string;
    streamId?: string;
    lessonsPerWeek: number;
    preferredDoubleLessons?: number;
  }) => Promise<void>;
  onUpdateAllocation: (input: {
    id: string;
    lessonsPerWeek?: number;
    preferredDoubleLessons?: number;
  }) => Promise<void>;
  onDeleteAllocation: (id: string) => Promise<void>;
  onUpsertRules: (
    input: Partial<TeacherWorkloadRules> & { termId: string; teacherId: string },
  ) => Promise<void>;
  onRunPreflight: () => Promise<TimetablePreflightResult | null>;
  /** Existing lessons in the term — used to warn before a replace run deletes them. */
  existingLessonCount?: number;
  /** Jump to the school-day setup when there are no periods to plan into. */
  onSetUpSchoolDay?: () => void;
  onGenerate: (replaceExisting: boolean) => Promise<{
    createdCount: number;
    unresolvedCount: number;
    warnings: string[];
    entries?: Array<{
      id: string;
      subjectId: string;
      teacherId: string;
      dayTemplatePeriodId: string;
      streamId?: string | null;
      gradeLevelId?: string;
      isDoublePeriod?: boolean;
    }>;
  }>;
  onGenerated: (result?: {
    createdCount: number;
    unresolvedCount: number;
    warnings: string[];
    entries?: Array<{
      id: string;
      subjectId: string;
      teacherId: string;
      dayTemplatePeriodId: string;
      streamId?: string | null;
      gradeLevelId?: string;
      isDoublePeriod?: boolean;
    }>;
  }) => void;
}

const WEEKDAY_OPTIONS = [
  { value: 1, label: "Mon" },
  { value: 2, label: "Tue" },
  { value: 3, label: "Wed" },
  { value: 4, label: "Thu" },
  { value: 5, label: "Fri" },
  { value: 6, label: "Sat" },
  { value: 7, label: "Sun" },
] as const;

const STEPS = [
  { id: "allocations" as const, label: "Weekly lessons" },
  { id: "rules" as const, label: "Workload" },
  { id: "generate" as const, label: "Create" },
];

// Docked drawer width (desktop). Drag the left edge to adjust; persisted per device.
const DOCK_DEFAULT_W = 424; // 26.5rem
const DOCK_MIN_W = 360;
const DOCK_MAX_W = 720;
const DOCK_WIDTH_KEY = "timetable-autofill-dock-width";

const clampDockWidth = (value: number) =>
  Math.max(DOCK_MIN_W, Math.min(DOCK_MAX_W, Math.round(value)));

/** Plain-language narration while the generator runs. */
const GENERATION_STAGES = [
  "Setting up your classes…",
  "Placing lessons for every class…",
  "Keeping double lessons side by side…",
  "Balancing each teacher's week…",
  "Making sure no teacher is in two classes at once…",
  "Finishing your timetable…",
];

function toggleNumberInList(
  list: number[] | null | undefined,
  value: number,
): number[] {
  const current = list ?? [];
  return current.includes(value)
    ? current.filter((v) => v !== value)
    : [...current, value].sort((a, b) => a - b);
}

function Chip({
  on,
  danger,
  warn,
  children,
  onClick,
}: {
  on?: boolean;
  danger?: boolean;
  warn?: boolean;
  children: ReactNode;
  onClick: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={cn(
        tt.chip,
        tt.text.micro,
        tt.focus,
        "px-1.5 py-0.5",
        on && !danger && !warn && tt.chipOn,
        on && danger && tt.chipDanger,
        on && warn && tt.chipWarn,
      )}
    >
      {children}
    </button>
  );
}

export function TimetableAutoGenerateDrawer({
  open,
  onClose,
  initialStep = 0,
  scopeLabel,
  focusedGradeId,
  onFocusedGradeChange,
  termId,
  teachers,
  subjects,
  grades,
  availableSlotsPerClass,
  schoolDays = 5,
  periodNumbers = [1, 2, 3, 4, 5, 6, 7, 8],
  allocations,
  rules,
  loading,
  onCreateAllocation,
  onUpdateAllocation,
  onDeleteAllocation,
  onUpsertRules,
  onRunPreflight,
  existingLessonCount,
  onSetUpSchoolDay,
  onGenerate,
  onGenerated,
}: TimetableAutoGenerateDrawerProps) {
  const { toast } = useToast();
  const [stepIndex, setStepIndex] = useState(0);
  const [busy, setBusy] = useState(false);
  const [preflight, setPreflight] = useState<TimetablePreflightResult | null>(
    null,
  );
  const [selectedRulesTeacherId, setSelectedRulesTeacherId] = useState("");
  const [unavailDay, setUnavailDay] = useState(1);
  const [unavailPeriod, setUnavailPeriod] = useState(1);
  const [replaceExisting, setReplaceExisting] = useState(false);
  const [replaceAcknowledged, setReplaceAcknowledged] = useState(false);
  const [showAddForm, setShowAddForm] = useState(false);
  const [showByTeacher, setShowByTeacher] = useState(false);
  const [progressStage, setProgressStage] = useState<number | null>(null);
  const [rulesSaved, setRulesSaved] = useState(false);
  const plannerRef = useRef<TimetableWeeklyLessonsPlannerHandle>(null);
  const pendingRulesPatchRef = useRef<Partial<TeacherWorkloadRules>>({});
  const rulesSaveTimerRef = useRef<number | null>(null);
  const rulesSavedTimerRef = useRef<number | null>(null);
  const [isDesktopDock, setIsDesktopDock] = useState(true);

  useEffect(
    () => () => {
      if (rulesSaveTimerRef.current) window.clearTimeout(rulesSaveTimerRef.current);
      if (rulesSavedTimerRef.current) window.clearTimeout(rulesSavedTimerRef.current);
    },
    [],
  );

  useEffect(() => {
    const mql = window.matchMedia("(min-width: 1024px)");
    const apply = () => setIsDesktopDock(mql.matches);
    apply();
    mql.addEventListener("change", apply);
    return () => mql.removeEventListener("change", apply);
  }, []);

  // ── Resizable docked drawer (desktop) ───────────────────────────
  const [dockWidth, setDockWidth] = useState(DOCK_DEFAULT_W);
  const [dockResizing, setDockResizing] = useState(false);
  const dockDragRef = useRef<{ startX: number; startWidth: number } | null>(null);
  const dockWidthHydratedRef = useRef(false);

  useEffect(() => {
    try {
      const raw = window.localStorage.getItem(DOCK_WIDTH_KEY);
      if (raw) {
        const parsed = Number(raw);
        if (Number.isFinite(parsed)) setDockWidth(clampDockWidth(parsed));
      }
    } catch {
      // Ignore unavailable storage.
    }
  }, []);

  useEffect(() => {
    if (!dockWidthHydratedRef.current) {
      dockWidthHydratedRef.current = true;
      return;
    }
    try {
      window.localStorage.setItem(DOCK_WIDTH_KEY, String(dockWidth));
    } catch {
      // Ignore quota / private-mode failures.
    }
  }, [dockWidth]);

  const beginDockResize = (event: React.PointerEvent) => {
    event.preventDefault();
    dockDragRef.current = { startX: event.clientX, startWidth: dockWidth };
    setDockResizing(true);
  };

  useEffect(() => {
    if (!dockResizing) return;
    const onMove = (event: PointerEvent) => {
      const drag = dockDragRef.current;
      if (!drag) return;
      // Left edge: dragging left grows the drawer.
      setDockWidth(clampDockWidth(drag.startWidth + (drag.startX - event.clientX)));
    };
    const onEnd = () => setDockResizing(false);
    const previousUserSelect = document.body.style.userSelect;
    document.body.style.userSelect = "none";
    window.addEventListener("pointermove", onMove);
    window.addEventListener("pointerup", onEnd);
    window.addEventListener("pointercancel", onEnd);
    return () => {
      window.removeEventListener("pointermove", onMove);
      window.removeEventListener("pointerup", onEnd);
      window.removeEventListener("pointercancel", onEnd);
      document.body.style.userSelect = previousUserSelect;
    };
  }, [dockResizing]);

  const nudgeDock = (event: React.KeyboardEvent) => {
    const step = event.shiftKey ? 24 : 8;
    if (event.key === "ArrowLeft") {
      event.preventDefault();
      setDockWidth((w) => clampDockWidth(w + step));
    } else if (event.key === "ArrowRight") {
      event.preventDefault();
      setDockWidth((w) => clampDockWidth(w - step));
    } else if (event.key === "Home" || event.key === "Enter") {
      event.preventDefault();
      setDockWidth(DOCK_DEFAULT_W);
    }
  };

  // ── Hints modal ─────────────────────────────────────────
  const [hintsOpen, setHintsOpen] = useState(false);
  const HINTS_SEEN_KEY = "timetable-autofill-hints-seen";

  // First-ever open with nothing planned yet: show how the generator works.
  useEffect(() => {
    if (!open || allocations.length > 0) return;
    try {
      if (!window.localStorage.getItem(HINTS_SEEN_KEY)) {
        window.localStorage.setItem(HINTS_SEEN_KEY, "1");
        setHintsOpen(true);
      }
    } catch {
      // Ignore unavailable storage.
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  const [draftTeacherId, setDraftTeacherId] = useState("");
  const [draftSubjectId, setDraftSubjectId] = useState("");
  const [draftGradeId, setDraftGradeId] = useState("");
  const [draftStreamId, setDraftStreamId] = useState("");
  const [draftLessons, setDraftLessons] = useState(5);
  const [draftDoubles, setDraftDoubles] = useState(0);

  const step = STEPS[stepIndex];

  const teacherMap = useMemo(
    () => new Map(teachers.map((t) => [t.id, t.name])),
    [teachers],
  );
  const subjectMap = useMemo(
    () => new Map(subjects.map((s) => [s.id, s.name])),
    [subjects],
  );
  /** Keyed by both id forms so stored allocations resolve either way. */
  const gradeMap = useMemo(() => {
    const map = new Map<string, string>();
    for (const g of grades) {
      map.set(g.id, g.name);
      if (g.tenantGradeLevelId) map.set(g.tenantGradeLevelId, g.name);
    }
    return map;
  }, [grades]);

  const classCountFor = useCallback(
    (gradeLevelId: string) =>
      Math.max(1, tenantStreamIdsForGrade(gradeLevelId, grades).length),
    [grades],
  );

  const localPreflight = useMemo(
    () =>
      computeLocalPreflight({
        allocations,
        rules,
        availableSlotsPerClass,
        schoolDays,
        classCountFor,
      }),
    [allocations, rules, availableSlotsPerClass, schoolDays, classCountFor],
  );

  const activeRulesTeacherId =
    selectedRulesTeacherId || teachers[0]?.id || "";
  const activeRules =
    rules.find((r) => r.teacherId === activeRulesTeacherId) ?? null;

  const draftStreams =
    grades.find((g) => g.id === draftGradeId)?.streams ?? [];

  const teacherSubjects = useMemo(() => {
    const t = teachers.find((x) => x.id === draftTeacherId);
    if (!t?.subjectIds?.length) return subjects;
    const set = new Set(t.subjectIds);
    const filtered = subjects.filter((s) => set.has(s.id));
    return filtered.length ? filtered : subjects;
  }, [teachers, draftTeacherId, subjects]);

  const totalDemand = allocations.reduce((s, a) => s + a.lessonsPerWeek, 0);
  const teachersWithRules = new Set(rules.map((r) => r.teacherId)).size;
  const teachersInAlloc = new Set(allocations.map((a) => a.teacherId)).size;

  const handleAddAllocation = async () => {
    if (!draftTeacherId || !draftSubjectId || !draftGradeId || draftLessons < 1) {
      toast({
        title: "Missing fields",
        description: "Select teacher, subject, grade, and lessons per week.",
        variant: "destructive",
      });
      return;
    }
    setBusy(true);
    try {
      await onCreateAllocation({
        termId,
        teacherId: draftTeacherId,
        subjectId: draftSubjectId,
        gradeLevelId:
          resolveTenantGradeLevelIdForApi(draftGradeId, grades) ?? draftGradeId,
        streamId:
          resolveTenantStreamIdForApi(draftStreamId, draftGradeId, grades) ??
          undefined,
        lessonsPerWeek: draftLessons,
        preferredDoubleLessons: draftDoubles || undefined,
      });
      toast({ title: "Allocation added" });
      setShowAddForm(false);
      setDraftDoubles(0);
    } catch (err) {
      toast({
        title: "Could not add allocation",
        description: sanitizeTimetableUserMessage(err),
        variant: "destructive",
      });
    } finally {
      setBusy(false);
    }
  };

  const handleSaveRules = async (patch: Partial<TeacherWorkloadRules>) => {
    if (!activeRulesTeacherId) return;
    setBusy(true);
    try {
      await onUpsertRules({
        termId,
        teacherId: activeRulesTeacherId,
        totalLessonsPerWeek: activeRules?.totalLessonsPerWeek,
        maxLessonsPerDay: activeRules?.maxLessonsPerDay,
        minLessonsPerDay: activeRules?.minLessonsPerDay,
        doubleLessonsPerWeek: activeRules?.doubleLessonsPerWeek,
        maxConsecutiveLessons: activeRules?.maxConsecutiveLessons,
        minFreePeriodsPerDay: activeRules?.minFreePeriodsPerDay,
        preferredDays: activeRules?.preferredDays,
        avoidDays: activeRules?.avoidDays,
        preferredPeriodNumbers: activeRules?.preferredPeriodNumbers,
        avoidPeriodNumbers: activeRules?.avoidPeriodNumbers,
        preferredTimeOfDay: activeRules?.preferredTimeOfDay,
        unavailableSlots: activeRules?.unavailableSlots,
        ...patch,
      });
      setRulesSaved(true);
      if (rulesSavedTimerRef.current) {
        window.clearTimeout(rulesSavedTimerRef.current);
      }
      rulesSavedTimerRef.current = window.setTimeout(
        () => setRulesSaved(false),
        2000,
      );
    } catch (err) {
      toast({
        title: "Could not save rules",
        description: sanitizeTimetableUserMessage(err),
        variant: "destructive",
      });
    } finally {
      setBusy(false);
    }
  };

  /** Coalesce rapid field edits into one save instead of a network call per field. */
  const scheduleSaveRules = (patch: Partial<TeacherWorkloadRules>) => {
    pendingRulesPatchRef.current = {
      ...pendingRulesPatchRef.current,
      ...patch,
    };
    if (rulesSaveTimerRef.current) window.clearTimeout(rulesSaveTimerRef.current);
    rulesSaveTimerRef.current = window.setTimeout(() => {
      const merged = pendingRulesPatchRef.current;
      pendingRulesPatchRef.current = {};
      rulesSaveTimerRef.current = null;
      void handleSaveRules(merged);
    }, 500);
  };

  const handlePreflight = async () => {
    setBusy(true);
    try {
      const remote = await onRunPreflight();
      setPreflight(remote ?? localPreflight);
    } catch {
      setPreflight(localPreflight);
    } finally {
      setBusy(false);
    }
  };

  // Reset the drawer's panels each time it opens, and pre-flight the checks
  // when landing straight on the Create step. The resets and pre-flight run in
  // a microtask so the sheet can mount before we touch its panels.
  useEffect(() => {
    if (!open) return;
    const target = Math.min(
      Math.max(initialStep, 0),
      allocations.length > 0 ? STEPS.length - 1 : 0,
    );
    queueMicrotask(() => {
      setStepIndex(target);
      setPreflight(null);
      setShowAddForm(allocations.length === 0);
      if (target === STEPS.length - 1) void handlePreflight();
    });
  }, [open, initialStep]); // eslint-disable-line react-hooks/exhaustive-deps

  const handleGenerate = async () => {
    setBusy(true);
    setProgressStage(0);
    const ticker = window.setInterval(() => {
      setProgressStage((s) =>
        Math.min((s ?? 0) + 1, GENERATION_STAGES.length - 1),
      );
    }, 900);
    try {
      const result = await onGenerate(replaceExisting);
      const warnings = (result.warnings ?? []).filter(Boolean);
      const baseDescription = result.createdCount
        ? result.unresolvedCount
          ? `Placed ${result.createdCount} for teachers you assigned. ${result.unresolvedCount} left empty for later.`
          : `Placed ${result.createdCount} lessons. Empty cells stay free for later.`
        : "Assign teachers to subjects, then try again — or place lessons on the grid yourself.";
      toast({
        title: result.createdCount
          ? "Your timetable is ready to check"
          : "Nothing to place yet",
        description:
          warnings.length > 0
            ? `${baseDescription} ${warnings.slice(0, 2).join(" ")}`
            : baseDescription,
      });
      onGenerated(result);
      onClose();
    } catch (err) {
      toast({
        title: "We could not finish the timetable",
        description: sanitizeTimetableUserMessage(err),
        variant: "destructive",
      });
    } finally {
      window.clearInterval(ticker);
      setProgressStage(null);
      setBusy(false);
    }
  };

  const displayPreflight = preflight ?? localPreflight;
  const canContinueFromDemand = allocations.length > 0;
  const replaceWillRemoveLessons =
    replaceExisting && (existingLessonCount ?? 0) > 0;
  const canGenerate =
    displayPreflight.ok &&
    allocations.length > 0 &&
    (!replaceWillRemoveLessons || replaceAcknowledged);

  const goNext = async () => {
    if (stepIndex === 0 && !canContinueFromDemand) {
      toast({
        title: "Add lessons for at least one class",
        description:
          "Set the weekly lessons and a teacher for a class, save, and you'll be ready to continue.",
        variant: "destructive",
      });
      return;
    }
    // Step 1's planner holds edits in its own state — persist them before
    // moving on, otherwise leaving the step would throw them away.
    if (stepIndex === 0 && plannerRef.current?.hasUnsavedChanges()) {
      setBusy(true);
      try {
        await plannerRef.current.save();
      } finally {
        setBusy(false);
      }
      // Saving can fail (e.g. offline) — edits remain, so don't advance.
      if (plannerRef.current?.hasUnsavedChanges()) return;
    }
    if (stepIndex < STEPS.length - 1) {
      setStepIndex((i) => i + 1);
      if (stepIndex === 1) void handlePreflight();
    }
  };

  const goBack = () => {
    if (stepIndex > 0) setStepIndex((i) => i - 1);
  };

  const hintsDialog = (
    <Dialog open={hintsOpen} onOpenChange={setHintsOpen}>
      <DialogContent className="max-w-lg gap-0 overflow-hidden rounded-none border border-[#1a4d42]/12 bg-[#f8fbfa] p-0 dark:border-white/10 dark:bg-[#0c1a17]">
        <DialogHeader className="space-y-0 border-b border-[#1a4d42]/12 px-5 py-4 text-left dark:border-white/10">
          <DialogTitle
            className={cn(
              "flex items-center gap-2.5 font-semibold tracking-[-0.02em]",
              tt.text.title,
              tt.ink.strong,
            )}
          >
            <span className="flex h-7 w-7 shrink-0 items-center justify-center border border-[#246a59]/25 bg-[#246a59]/10 text-[#246a59] dark:border-[#7eb8a8]/25 dark:bg-[#246a59]/20 dark:text-[#7eb8a8]">
              <Lightbulb className="h-3.5 w-3.5" />
            </span>
            How auto-fill works
          </DialogTitle>
          <DialogDescription
            className={cn("mt-1", tt.text.caption, tt.ink.muted)}
          >
            Three steps — say what to place, set limits, create. About five
            minutes, and you can fine-tune everything afterwards.
          </DialogDescription>
        </DialogHeader>

        <div className="max-h-[60vh] overflow-y-auto px-5 py-4">
          <ol className="space-y-3">
            {[
              {
                Icon: ListChecks,
                title: "Weekly lessons — say what to place",
                body: 'For each class, pick the subject, how many lessons a week, and the teacher. Tap "Use suggested" to fill this from the class\'s weekly lessons.',
              },
              {
                Icon: Scale,
                title: "Workload — optional limits",
                body: "Set gentle limits per teacher: daily and weekly caps, no-doubles days, morning or afternoon preference. Skip it and auto-fill simply balances everyone's week.",
              },
              {
                Icon: Sparkles,
                title: "Create — build the week",
                body: 'Auto-fill places every lesson and never puts a teacher in two classes at once. Nothing reaches teachers until you click "Share with teachers".',
              },
            ].map(({ Icon, title, body }, i) => (
              <li key={title} className="flex items-start gap-3">
                <span
                  className={cn(
                    tt.numeral,
                    "mt-0.5 flex h-7 shrink-0 flex-col items-center justify-center border border-[#1a4d42]/12 bg-white dark:border-white/10 dark:bg-[#071411]",
                  )}
                >
                  <Icon className="h-3.5 w-3.5 text-[#246a59] dark:text-[#7eb8a8]" />
                </span>
                <div className="min-w-0">
                  <p
                    className={cn(
                      "font-semibold",
                      tt.text.small,
                      tt.ink.strong,
                    )}
                  >
                    <span className={cn(tt.ink.faint, "mr-1.5")}>{i + 1}.</span>
                    {title}
                  </p>
                  <p className={cn("mt-0.5 leading-relaxed", tt.text.caption, tt.ink.muted)}>
                    {body}
                  </p>
                </div>
              </li>
            ))}
          </ol>

          <p
            className={cn(
              "mt-5 flex items-center gap-1.5 font-semibold uppercase tracking-[0.12em]",
              tt.text.micro,
              tt.ink.faint,
            )}
          >
            Good to know
          </p>
          <div className="mt-2 grid gap-px border border-[#1a4d42]/12 bg-[#1a4d42]/10 dark:border-white/10 dark:bg-white/10 sm:grid-cols-2">
            {[
              {
                Icon: MousePointerClick,
                title: "Fine-tune by hand",
                body: "After auto-fill, move any lesson on the grid — your changes are kept.",
              },
              {
                Icon: Eraser,
                title: "Starting over",
                body: '"Replace existing lessons" (step 3) wipes the grid first. Off by default, and it asks twice.',
              },
              {
                Icon: AlertTriangle,
                title: "When something doesn't fit",
                body: "That slot is left empty and auto-fill tells you why. Open Issues to fix it, then create again.",
              },
              {
                Icon: Lightbulb,
                title: "Use doubles wisely",
                body: "Doubles place a subject in two back-to-back periods — ideal for labs and creative arts.",
              },
            ].map(({ Icon, title, body }) => (
              <div
                key={title}
                className="bg-[#f8fbfa] p-3 dark:bg-[#0c1a17]"
              >
                <p
                  className={cn(
                    "flex items-center gap-1.5 font-semibold",
                    tt.text.caption,
                    tt.ink.strong,
                  )}
                >
                  <Icon className="h-3 w-3 shrink-0 text-[#246a59] dark:text-[#7eb8a8]" />
                  {title}
                </p>
                <p
                  className={cn(
                    "mt-1 leading-relaxed",
                    tt.text.caption,
                    tt.ink.muted,
                  )}
                >
                  {body}
                </p>
              </div>
            ))}
          </div>
        </div>

        <div className="flex items-center justify-between gap-3 border-t border-[#1a4d42]/12 px-5 py-3 dark:border-white/10">
          <p className={cn(tt.text.caption, tt.ink.faint)}>
            Reopen anytime from the Hints button.
          </p>
          <Button
            type="button"
            size="sm"
            className={cn("h-8 rounded-none font-medium", tt.accentBtn)}
            onClick={() => setHintsOpen(false)}
          >
            Got it — let&apos;s go
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );

  const panel = (
      <>
        <div className="shrink-0 border-b border-[#1a4d42]/12 px-3 py-2 dark:border-white/10">
          <div className="flex items-center justify-between gap-2">
            <div className="min-w-0">
              <h2 className={cn(tt.text.body, tt.ink.strong, "truncate font-semibold tracking-[-0.02em]")}>
                Auto-fill timetable
              </h2>
              <p className={cn(tt.text.caption, tt.ink.muted, "truncate")}>
                {stepIndex === 0
                  ? [
                      grades.find(
                        (g) =>
                          g.id === focusedGradeId ||
                          g.tenantGradeLevelId === focusedGradeId,
                      )?.name,
                      totalDemand > 0 ? `${totalDemand} lessons` : null,
                    ]
                      .filter(Boolean)
                      .join(" · ") ||
                    scopeLabel ||
                    "Set weekly lessons by class"
                  : stepIndex === 1
                    ? `Optional · ${teachersWithRules}/${teachersInAlloc || teachers.length} teachers`
                    : "Creates the week for every class"}
              </p>
            </div>
            <div className="flex shrink-0 items-center gap-1">
              <button
                type="button"
                onClick={() => setHintsOpen(true)}
                className={cn(
                  tt.focus,
                  "flex h-7 items-center gap-1 px-1.5 font-medium transition-colors",
                  tt.text.caption,
                  tt.ink.muted,
                  "hover:bg-[#e8f2ef] hover:text-[#0a1f1a] dark:hover:bg-white/5 dark:hover:text-white",
                )}
                aria-label="Hints on how auto-fill works"
              >
                <Lightbulb className="h-3.5 w-3.5" />
                Hints
              </button>
              {isDesktopDock ? (
                <button
                  type="button"
                  onClick={onClose}
                  className={cn(tt.focus, "flex h-7 w-7 shrink-0 items-center justify-center text-[#1a4d42]/45 hover:bg-[#e8f2ef] hover:text-[#0a1f1a] dark:hover:bg-white/5 dark:hover:text-white")}
                  aria-label="Close auto-fill"
                >
                  <X className="h-3.5 w-3.5" />
                </button>
              ) : (
                <>
                  <SheetTitle className="sr-only">Auto-fill timetable</SheetTitle>
                  <SheetDescription className="sr-only">
                    Set weekly lessons, optional teacher limits, then place the week on the grid.
                  </SheetDescription>
                </>
              )}
            </div>
          </div>

          <ol className="mt-2 flex gap-px border border-[#1a4d42]/12 bg-[#e8f2ef] dark:border-white/10 dark:bg-white/10">
            {STEPS.map((s, i) => {
              const done = i < stepIndex;
              const active = i === stepIndex;
              return (
                <li key={s.id} className="flex min-w-0 flex-1">
                  <button
                    type="button"
                    onClick={() => {
                      if (i <= stepIndex || (i === 1 && canContinueFromDemand)) {
                        setStepIndex(i);
                      }
                    }}
                    className={cn(
                      tt.focus,
                      "flex min-w-0 flex-1 items-center justify-center gap-1 px-1 py-1.5 text-left transition-colors",
                      active && "bg-[#0a1f1a] text-white dark:bg-[#246a59]",
                      done && !active && "bg-white text-emerald-700 dark:bg-[#0c1a17] dark:text-emerald-300",
                      !active && !done && cn("bg-white dark:bg-[#071411]", tt.ink.muted),
                    )}
                  >
                    <span
                      className={cn(
                        tt.numeral,
                        "flex h-4 w-4 shrink-0 items-center justify-center text-[9px] font-bold",
                        active && "bg-white/20 text-white",
                        done && !active && "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/50",
                        !active &&
                          !done &&
                          cn(tt.ink.faint, "bg-[#e8f2ef] dark:bg-white/10"),
                      )}
                    >
                      {done ? (
                        <Check className="h-2.5 w-2.5" strokeWidth={3} />
                      ) : (
                        i + 1
                      )}
                    </span>
                    <span
                      className={cn(
                        tt.text.micro,
                        "truncate font-semibold tracking-[-0.01em]",
                        active ? "text-white" : undefined,
                      )}
                    >
                      {s.label}
                    </span>
                  </button>
                </li>
              );
            })}
          </ol>
        </div>

        <div className="flex min-h-0 flex-1 flex-col overflow-hidden">
          <div className="min-h-0 flex-1 overflow-y-auto px-3 py-2">
          {loading && (
            <div className={cn(tt.text.small, tt.ink.muted, "mb-2 flex items-center gap-2")}>
              <Loader2 className="h-3.5 w-3.5 animate-spin" /> Loading…
            </div>
          )}

          {/* ── Demand ── */}
          {step.id === "allocations" && (
            <div className="space-y-2">

              <TimetableWeeklyLessonsPlanner
                ref={plannerRef}
                termId={termId}
                grades={grades}
                subjects={subjects}
                teachers={teachers}
                allocations={allocations}
                availableSlotsPerClass={availableSlotsPerClass}
                focusedGradeId={focusedGradeId}
                onFocusedGradeChange={onFocusedGradeChange}
                onCreateAllocation={onCreateAllocation}
                onUpdateAllocation={onUpdateAllocation}
                onDeleteAllocation={onDeleteAllocation}
                onSetUpSchoolDay={onSetUpSchoolDay}
              />

              <div className="border border-[#1a4d42]/12 dark:border-white/10">
                <button
                  type="button"
                  onClick={() => setShowByTeacher((v) => !v)}
                  className={cn(tt.focus, "flex w-full items-center justify-between gap-2 px-2 py-1.5 text-left")}
                >
                  <span className={cn(tt.text.caption, "font-medium", tt.ink.base)}>
                    By teacher
                  </span>
                  <span className={cn(tt.text.micro, tt.numeral, tt.ink.faint, "flex items-center gap-1.5")}>
                    {allocations.length} rows
                    <ChevronRight
                      className={cn(
                        "h-3.5 w-3.5 transition",
                        showByTeacher && "rotate-90",
                      )}
                    />
                  </span>
                </button>

                {showByTeacher && (
                  <div className={cn(tt.border.hair, "space-y-3 border-t p-3")}>
              {allocations.length > 0 && (
                <ul className="divide-y divide-[#1a4d42]/10 overflow-hidden rounded-none border border-[#1a4d42]/12 dark:divide-white/10 dark:border-white/10">
                  {allocations.map((a) => {
                    const streamName = a.streamId
                      ? grades
                          .find((g) => g.id === a.gradeLevelId)
                          ?.streams?.find(
                            (s) =>
                              s.tenantStreamId === a.streamId ||
                              s.streamId === a.streamId,
                          )?.name
                      : null;
                    return (
                      <li
                        key={a.id}
                        className="flex items-center gap-3 bg-white px-3 py-2.5 dark:bg-[#071411]"
                      >
                        <div className="min-w-0 flex-1">
                          <p className={cn(tt.text.body, tt.ink.strong, "truncate font-medium")}>
                            {teacherMap.get(a.teacherId) ?? "Teacher"}
                            <span className={cn("font-normal", tt.ink.faint)}>
                              {" "}
                              · {subjectMap.get(a.subjectId) ?? "Subject"}
                            </span>
                          </p>
                          <p className={cn(tt.text.caption, tt.ink.muted, "truncate")}>
                            {gradeMap.get(a.gradeLevelId) ?? "Grade"}
                            {streamName ? ` · ${streamName}` : ""}
                          </p>
                        </div>
                        <Input
                          type="number"
                          min={1}
                          className={cn(tt.text.small, tt.numeral, "h-8 w-16 text-center")}
                          defaultValue={a.lessonsPerWeek}
                          key={`${a.id}-${a.lessonsPerWeek}`}
                          onBlur={(e) => {
                            const n = Number(e.target.value);
                            if (n >= 1 && n !== a.lessonsPerWeek) {
                              void onUpdateAllocation({
                                id: a.id,
                                lessonsPerWeek: n,
                              });
                            }
                          }}
                        />
                        <Button
                          type="button"
                          size="icon"
                          variant="ghost"
                          className={cn(tt.ink.faint, "h-8 w-8 hover:text-red-600")}
                          onClick={() => void onDeleteAllocation(a.id)}
                        >
                          <Trash2 className="h-3.5 w-3.5" />
                        </Button>
                      </li>
                    );
                  })}
                </ul>
              )}

              {!showAddForm ? (
                <Button
                  type="button"
                  variant="outline"
                  className="w-full border-dashed"
                  onClick={() => setShowAddForm(true)}
                >
                  <Plus className="mr-1.5 h-4 w-4" />
                  Add allocation
                </Button>
              ) : (
                <div className={cn(tt.panelMuted, "space-y-3 p-3.5")}>
                  <div className="flex items-center justify-between">
                    <p className={cn(tt.text.small, tt.ink.strong, "font-semibold")}>
                      New allocation
                    </p>
                    <button
                      type="button"
                      className={cn(tt.focus, tt.text.caption, tt.ink.muted, "hover:underline")}
                      onClick={() => setShowAddForm(false)}
                    >
                      Cancel
                    </button>
                  </div>
                  <div className="grid gap-2.5 sm:grid-cols-2">
                    <div className="space-y-1 sm:col-span-2">
                      <Label className={tt.text.caption}>Teacher</Label>
                      <Select
                        value={draftTeacherId || undefined}
                        onValueChange={setDraftTeacherId}
                      >
                        <SelectTrigger className="h-9">
                          <SelectValue placeholder="Select teacher" />
                        </SelectTrigger>
                        <SelectContent>
                          {teachers.map((t) => (
                            <SelectItem key={t.id} value={t.id}>
                              {t.name}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>
                    <div className="space-y-1">
                      <Label className={tt.text.caption}>Subject</Label>
                      <Select
                        value={draftSubjectId || undefined}
                        onValueChange={setDraftSubjectId}
                      >
                        <SelectTrigger className="h-9">
                          <SelectValue placeholder="Subject" />
                        </SelectTrigger>
                        <SelectContent>
                          {teacherSubjects.map((s) => (
                            <SelectItem key={s.id} value={s.id}>
                              {s.name}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>
                    <div className="space-y-1">
                      <Label className={tt.text.caption}>Grade</Label>
                      <Select
                        value={draftGradeId || undefined}
                        onValueChange={(v) => {
                          setDraftGradeId(v);
                          setDraftStreamId("");
                        }}
                      >
                        <SelectTrigger className="h-9">
                          <SelectValue placeholder="Grade" />
                        </SelectTrigger>
                        <SelectContent>
                          {grades.map((g) => (
                            <SelectItem key={g.id} value={g.id}>
                              {g.name}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>
                    {draftStreams.length > 0 && (
                      <div className="space-y-1 sm:col-span-2">
                        <Label className={tt.text.caption}>Stream (optional)</Label>
                        <Select
                          value={draftStreamId || "__all__"}
                          onValueChange={(v) =>
                            setDraftStreamId(v === "__all__" ? "" : v)
                          }
                        >
                          <SelectTrigger className="h-9">
                            <SelectValue placeholder="All streams" />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="__all__">All streams</SelectItem>
                            {draftStreams.map((s) => {
                              // A stream without an id cannot be stored.
                              const streamValue =
                                s.tenantStreamId || s.streamId;
                              if (!streamValue) return null;
                              return (
                                <SelectItem
                                  key={streamValue}
                                  value={streamValue}
                                >
                                  {s.name}
                                </SelectItem>
                              );
                            })}
                          </SelectContent>
                        </Select>
                      </div>
                    )}
                    <div className="space-y-1">
                      <Label className={tt.text.caption}>Lessons / week</Label>
                      <Input
                        type="number"
                        min={1}
                        className="h-9"
                        value={draftLessons}
                        onChange={(e) =>
                          setDraftLessons(Math.max(1, Number(e.target.value) || 1))
                        }
                      />
                    </div>
                    <div className="space-y-1">
                      <Label className={tt.text.caption}>Preferred doubles</Label>
                      <Input
                        type="number"
                        min={0}
                        className="h-9"
                        value={draftDoubles}
                        onChange={(e) =>
                          setDraftDoubles(Math.max(0, Number(e.target.value) || 0))
                        }
                      />
                    </div>
                  </div>
                  <Button
                    type="button"
                    className={cn("w-full", tt.accentBtn)}
                    disabled={busy}
                    onClick={() => void handleAddAllocation()}
                  >
                    {busy ? (
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    ) : (
                      <Plus className="mr-2 h-4 w-4" />
                    )}
                    Add to demand
                  </Button>
                </div>
              )}
                  </div>
                )}
              </div>
            </div>
          )}

          {/* ── Rules ── */}
          {step.id === "rules" && (
            <div className="space-y-3">
              <div className="flex items-center gap-2">
                <Select
                  value={activeRulesTeacherId || undefined}
                  onValueChange={setSelectedRulesTeacherId}
                >
                  <SelectTrigger className={cn("h-8 min-w-0 flex-1", tt.text.small)}>
                    <SelectValue placeholder="Select teacher" />
                  </SelectTrigger>
                  <SelectContent>
                    {teachers.map((t) => (
                      <SelectItem key={t.id} value={t.id}>
                        {t.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                <span className={cn(tt.text.micro, tt.numeral, tt.ink.faint, "shrink-0")}>
                  {teachersWithRules}/{teachersInAlloc || teachers.length} set
                </span>
              </div>

              {activeRulesTeacherId && (
                <div className="space-y-3">
                  <section className="space-y-1.5">
                    <div className="flex items-center justify-between gap-2">
                      <p className={tt.eyebrow}>Limits</p>
                      {rulesSaved ? (
                        <span className={cn(tt.text.micro, "font-medium text-emerald-600 dark:text-emerald-400")}>
                          Saved ✓
                        </span>
                      ) : null}
                    </div>
                    <div className="grid grid-cols-2 gap-1.5">
                      <label className="col-span-2 space-y-0.5">
                        <span className={cn(tt.text.micro, "font-medium", tt.ink.muted)}>
                          Lessons a week
                        </span>
                        <Input
                          type="number"
                          min={0}
                          className={cn("h-8", tt.text.small)}
                          defaultValue={activeRules?.totalLessonsPerWeek ?? ""}
                          key={`${activeRulesTeacherId}-total-${activeRules?.id ?? "new"}`}
                          title="Should match this teacher’s allocation sum"
                          onBlur={(e) => {
                            const raw = e.target.value;
                            scheduleSaveRules({
                              totalLessonsPerWeek:
                                raw === "" ? null : Number(raw),
                            });
                          }}
                        />
                      </label>
                      {(
                        [
                          [
                            "maxLessonsPerDay",
                            "Most lessons a day",
                            "e.g. 6 — no more than this many in one day",
                          ],
                          [
                            "minLessonsPerDay",
                            "Fewest lessons a day",
                            "e.g. 3 — at least this many each day",
                          ],
                          [
                            "doubleLessonsPerWeek",
                            "Double lessons a week",
                            "Two of the same subject back-to-back",
                          ],
                          [
                            "maxConsecutiveLessons",
                            "Most lessons in a row",
                            "e.g. 2 — avoid long unbroken stretches",
                          ],
                          [
                            "minFreePeriodsPerDay",
                            "Free periods a day",
                            "e.g. 1 — at least one gap each day",
                          ],
                        ] as const
                      ).map(([key, label, hint]) => (
                        <label key={key} className="space-y-0.5" title={hint}>
                          <span
                            className={cn(tt.text.micro, "font-medium", tt.ink.muted)}
                            title={hint}
                          >
                            {label}
                          </span>
                          <Input
                            type="number"
                            min={0}
                            className={cn("h-8", tt.text.small)}
                            title={hint}
                            defaultValue={
                              (activeRules?.[key] as number | null | undefined) ??
                              ""
                            }
                            key={`${activeRulesTeacherId}-${key}-${activeRules?.id ?? "new"}`}
                            onBlur={(e) => {
                              const raw = e.target.value;
                              scheduleSaveRules({
                                [key]: raw === "" ? null : Number(raw),
                              } as Partial<TeacherWorkloadRules>);
                            }}
                          />
                        </label>
                      ))}
                    </div>
                  </section>

                  <section className="space-y-1.5">
                    <p className={tt.eyebrow}>Preferences</p>
                    <div className="space-y-1">
                      <p className={cn(tt.text.micro, "font-medium", tt.ink.muted)}>
                        Time of day
                      </p>
                      <div className="flex flex-wrap gap-1">
                        {(
                          [
                            ["ANY", "Any", CircleDot],
                            ["MORNING", "Morning", Sun],
                            ["EVENING", "Evening", Moon],
                          ] as const
                        ).map(([value, label, Icon]) => {
                          const current =
                            (activeRules?.preferredTimeOfDay as
                              | PreferredTimeOfDay
                              | null
                              | undefined) ?? "ANY";
                          return (
                            <Chip
                              key={value}
                              on={current === value}
                              onClick={() =>
                                void handleSaveRules({
                                  preferredTimeOfDay: value,
                                })
                              }
                            >
                              <Icon className="mr-1 h-3 w-3" />
                              {label}
                            </Chip>
                          );
                        })}
                      </div>
                    </div>
                    {(
                      [
                        [
                          "Prefer days",
                          activeRules?.preferredDays,
                          "preferredDays",
                          false,
                        ],
                        ["Avoid days", activeRules?.avoidDays, "avoidDays", true],
                      ] as const
                    ).map(([label, values, key, danger]) => (
                      <div key={key} className="space-y-1">
                        <p className={cn(tt.text.micro, "font-medium", tt.ink.muted)}>
                          {label}
                        </p>
                        <div className="flex flex-wrap gap-1">
                          {WEEKDAY_OPTIONS.map((d) => (
                            <Chip
                              key={`${key}-${d.value}`}
                              danger={danger}
                              on={values?.includes(d.value)}
                              onClick={() =>
                                void handleSaveRules({
                                  [key]: toggleNumberInList(values, d.value),
                                })
                              }
                            >
                              {d.label}
                            </Chip>
                          ))}
                        </div>
                      </div>
                    ))}
                    {(
                      [
                        [
                          "Prefer periods",
                          activeRules?.preferredPeriodNumbers,
                          "preferredPeriodNumbers",
                          false,
                        ],
                        [
                          "Avoid periods",
                          activeRules?.avoidPeriodNumbers,
                          "avoidPeriodNumbers",
                          true,
                        ],
                      ] as const
                    ).map(([label, values, key, warn]) => (
                      <div key={key} className="space-y-1">
                        <p className={cn(tt.text.micro, "font-medium", tt.ink.muted)}>
                          {label}
                        </p>
                        <div className="flex flex-wrap gap-1">
                          {periodNumbers.map((p) => (
                            <Chip
                              key={`${key}-${p}`}
                              warn={warn}
                              on={values?.includes(p)}
                              onClick={() =>
                                void handleSaveRules({
                                  [key]: toggleNumberInList(values, p),
                                })
                              }
                            >
                              P{p}
                            </Chip>
                          ))}
                        </div>
                      </div>
                    ))}
                  </section>

                  <section className="space-y-1.5">
                    <p className={tt.eyebrow}>Blocked slots</p>
                    <div className="flex items-center gap-1.5">
                      <Select
                        value={String(unavailDay)}
                        onValueChange={(v) => setUnavailDay(Number(v))}
                      >
                        <SelectTrigger className={cn("h-8 w-[4.5rem]", tt.text.caption)}>
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          {WEEKDAY_OPTIONS.map((d) => (
                            <SelectItem
                              key={d.value}
                              value={String(d.value)}
                            >
                              {d.label}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <Select
                        value={String(unavailPeriod)}
                        onValueChange={(v) => setUnavailPeriod(Number(v))}
                      >
                        <SelectTrigger className={cn("h-8 w-[4.25rem]", tt.text.caption)}>
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          {periodNumbers.map((p) => (
                            <SelectItem key={p} value={String(p)}>
                              P{p}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <Button
                        type="button"
                        size="sm"
                        variant="outline"
                        className={cn("h-8 px-2", tt.text.caption)}
                        disabled={busy}
                        onClick={() => {
                          const existing = activeRules?.unavailableSlots ?? [];
                          if (
                            existing.some(
                              (s) =>
                                s.dayOfWeek === unavailDay &&
                                s.periodNumber === unavailPeriod,
                            )
                          )
                            return;
                          void handleSaveRules({
                            unavailableSlots: [
                              ...existing,
                              {
                                dayOfWeek: unavailDay,
                                periodNumber: unavailPeriod,
                              },
                            ],
                          });
                        }}
                      >
                        <Plus className="mr-1 h-3 w-3" />
                        Block
                      </Button>
                    </div>
                    {(activeRules?.unavailableSlots ?? []).length > 0 ? (
                      <ul className="flex flex-wrap gap-1">
                        {(activeRules?.unavailableSlots ?? []).map((s, i) => (
                          <li key={`${s.dayOfWeek}-${s.periodNumber}-${i}`}>
                            <button
                              type="button"
                              className={cn(tt.focus, tt.text.micro, tt.ink.base, "inline-flex items-center gap-1 border border-[#1a4d42]/12 px-1.5 py-0.5 hover:border-red-300 hover:text-red-600 dark:border-white/10")}
                              onClick={() =>
                                void handleSaveRules({
                                  unavailableSlots: (
                                    activeRules?.unavailableSlots ?? []
                                  ).filter(
                                    (x) =>
                                      !(
                                        x.dayOfWeek === s.dayOfWeek &&
                                        x.periodNumber === s.periodNumber
                                      ),
                                  ),
                                })
                              }
                            >
                              {WEEKDAY_OPTIONS.find((d) => d.value === s.dayOfWeek)
                                ?.label ?? `D${s.dayOfWeek}`}{" "}
                              P{s.periodNumber}
                              <X className="h-2.5 w-2.5" />
                            </button>
                          </li>
                        ))}
                      </ul>
                    ) : (
                      <p className={cn(tt.text.micro, tt.ink.faint)}>
                        Assemblies and duties — never scheduled here.
                      </p>
                    )}
                  </section>
                </div>
              )}
            </div>
          )}

          {/* ── Generate ── */}
          {step.id === "generate" && (
            <div className="space-y-3">
              <div
                className={cn(
                  "border px-2.5 py-2",
                  displayPreflight.ok
                    ? "border-emerald-200 bg-emerald-50/50 dark:border-emerald-900/50 dark:bg-emerald-950/20"
                    : "border-amber-200 bg-amber-50/50 dark:border-amber-900/50 dark:bg-amber-950/20",
                )}
              >
                <div className="flex items-center gap-2">
                  {displayPreflight.ok ? (
                    <CheckCircle2 className="h-3.5 w-3.5 shrink-0 text-emerald-600" />
                  ) : (
                    <AlertTriangle className="h-3.5 w-3.5 shrink-0 text-amber-600" />
                  )}
                  <div className="min-w-0 flex-1">
                    <p className={cn(tt.text.small, tt.ink.strong, "font-semibold")}>
                      {displayPreflight.ok
                        ? "Ready to generate"
                        : "Fix issues first"}
                    </p>
                    <p className={cn(tt.text.micro, tt.numeral, tt.ink.muted)}>
                      {`${displayPreflight.totalAllocatedLessons} lessons · ~${displayPreflight.totalAvailableSlots}/class`}
                      {displayPreflight.ok
                        ? " · preferences will nudge placement"
                        : ""}
                    </p>
                  </div>
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    className={cn("h-7 shrink-0 px-2", tt.text.micro)}
                    disabled={busy}
                    onClick={() => void handlePreflight()}
                  >
                    Refresh
                  </Button>
                </div>
                {displayPreflight.issues.length > 0 ? (
                  <ul className="mt-2 space-y-1">
                    {displayPreflight.issues.map((issue, i) => (
                      <li
                        key={`${issue.code}-${i}`}
                        className={cn(tt.text.caption, tt.ink.base, "flex items-start gap-1.5")}
                      >
                        <AlertTriangle
                          className={cn(
                            "mt-0.5 h-3 w-3 shrink-0",
                            issue.severity === "error"
                              ? "text-red-500"
                              : "text-amber-500",
                          )}
                        />
                        {issue.message}
                      </li>
                    ))}
                  </ul>
                ) : null}
              </div>

              {progressStage !== null ? (
                <div className="border border-[#246a59]/30 bg-[#246a59]/5 px-2.5 py-2">
                  <p className={cn(tt.text.small, "flex items-center gap-1.5 font-semibold text-[#246a59] dark:text-[#7eb8a8]")}>
                    <Loader2 className="h-3.5 w-3.5 animate-spin" />
                    Creating your timetable
                  </p>
                  <ol className="mt-1.5 space-y-1">
                    {GENERATION_STAGES.map((stage, i) => (
                      <li
                        key={stage}
                        className={cn(
                          tt.text.caption,
                          "flex items-center gap-1.5 transition-colors",
                          i < progressStage
                            ? tt.ink.muted
                            : i === progressStage
                              ? cn("font-medium", tt.ink.strong)
                              : tt.ink.faint,
                        )}
                      >
                        {i < progressStage ? (
                          <Check
                            className="h-3 w-3 shrink-0 text-emerald-600"
                            strokeWidth={3}
                          />
                        ) : (
                          <span
                            className={cn(
                              "h-1.5 w-1.5 shrink-0 rounded-none",
                              i === progressStage
                                ? "bg-[#246a59]"
                                : "bg-[#e8f2ef] dark:bg-white/10",
                            )}
                            aria-hidden
                          />
                        )}
                        {stage}
                      </li>
                    ))}
                  </ol>
                </div>
              ) : null}

              <label className="flex cursor-pointer items-start gap-2">
                <input
                  type="checkbox"
                  className="mt-0.5"
                  checked={replaceExisting}
                  onChange={(e) => {
                    setReplaceExisting(e.target.checked);
                    if (!e.target.checked) setReplaceAcknowledged(false);
                  }}
                />
                <span>
                  <span className={cn(tt.text.small, tt.ink.strong, "block font-medium")}>
                    Replace current lessons
                  </span>
                  <span className={cn(tt.text.micro, tt.ink.faint, "mt-0.5 block")}>
                    Clears the grid before generating. Leave unchecked to keep
                    the grid and fill gaps only.
                  </span>
                </span>
              </label>

              {replaceWillRemoveLessons ? (
                <label className="mt-2 flex cursor-pointer items-start gap-2 border border-amber-300 bg-amber-50 px-2.5 py-2 dark:border-amber-900/60 dark:bg-amber-950/20">
                  <input
                    type="checkbox"
                    className="mt-0.5"
                    checked={replaceAcknowledged}
                    onChange={(e) => setReplaceAcknowledged(e.target.checked)}
                  />
                  <span className={cn(tt.text.caption, "text-amber-800 dark:text-amber-200")}>
                    This will remove {existingLessonCount} existing lesson
                    {(existingLessonCount ?? 0) === 1 ? "" : "s"} first. I
                    understand.
                  </span>
                </label>
              ) : null}
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between gap-2 border-t border-[#1a4d42]/10 bg-[#f8fbfa] px-3 py-2 dark:border-white/10 dark:bg-[#0c1a17]">
          <div className="flex items-center gap-1">
            <Button
              type="button"
              variant="ghost"
              size="sm"
              disabled={stepIndex === 0 || busy}
              onClick={goBack}
            >
              <ChevronLeft className="mr-1 h-4 w-4" />
              Back
            </Button>
            {stepIndex === 1 ? (
              <Button
                type="button"
                variant="ghost"
                size="sm"
                className={cn(tt.ink.muted, "hover:text-[#0a1f1a] dark:hover:text-white")}
                disabled={busy}
                onClick={goNext}
              >
                Skip for now
              </Button>
            ) : null}
          </div>

          {stepIndex === 0 && !canContinueFromDemand ? (
            <span className={cn(tt.text.caption, tt.ink.faint, "hidden md:inline")}>
              Save lessons for at least one class to continue.
            </span>
          ) : null}

          {stepIndex < STEPS.length - 1 ? (
            <Button
              type="button"
              size="sm"
              className={tt.accentBtn}
              disabled={busy || (stepIndex === 0 && !canContinueFromDemand)}
              onClick={goNext}
            >
              Continue
              <ChevronRight className="ml-1 h-4 w-4" />
            </Button>
          ) : (
            <Button
              type="button"
              size="sm"
              className={tt.accentBtn}
              disabled={busy || !canGenerate}
              onClick={() => void handleGenerate()}
            >
              {busy ? (
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              ) : (
                <Sparkles className="mr-2 h-4 w-4" />
              )}
              {busy ? "Creating…" : "Auto-fill timetable"}
            </Button>
          )}
        </div>
        </div>
      </>
  );

  if (!open) return null;

  if (isDesktopDock) {
    return (
      <aside
        data-timetable-no-print
        style={{ width: dockWidth }}
        className="relative hidden min-h-0 shrink-0 flex-col border-l border-[#1a4d42]/12 bg-white dark:border-white/10 dark:bg-[#0c1a17] lg:flex"
      >
        <div
          role="separator"
          aria-orientation="vertical"
          aria-label="Resize auto-fill drawer"
          aria-valuenow={dockWidth}
          aria-valuemin={DOCK_MIN_W}
          aria-valuemax={DOCK_MAX_W}
          tabIndex={0}
          title="Drag to resize · double-click to reset"
          onPointerDown={beginDockResize}
          onKeyDown={nudgeDock}
          onDoubleClick={(event) => {
            event.preventDefault();
            setDockWidth(DOCK_DEFAULT_W);
          }}
          className={cn(
            "absolute -left-1 top-0 z-40 h-full w-2.5 cursor-col-resize touch-none select-none",
            "before:absolute before:inset-y-0 before:left-0 before:w-px before:bg-transparent before:transition-colors",
            "hover:before:bg-[#246a59]/50 focus-visible:outline-none focus-visible:before:bg-[#246a59]",
            dockResizing && "before:w-0.5 before:bg-[#246a59]",
          )}
        />
        {panel}
        {hintsDialog}
      </aside>
    );
  }

  return (
    <Sheet open={open} onOpenChange={(o) => !o && onClose()}>
      <SheetContent
        side="right"
        data-timetable-portal
        className="flex w-full flex-col gap-0 overflow-hidden p-0 sm:max-w-lg"
      >
        {panel}
        {hintsDialog}
      </SheetContent>
    </Sheet>
  );
}
